repo_url: https://github.com/flanksource/platform-cli
repo_name: platform-cli
site_name: platform-cli
theme:
  name: "material"
  palette:
    primary: "royalblue"
  logo: "img/favicon.png"
extra:
  social:
    - type: "github"
      link: "https://github.com/flanksource"
      icon: fontawesome/brands/github-alt
markdown_extensions:
  - admonition
  - fenced_code
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - codehilite:
      linenums: true
nav:
        - User Guide:
              - Quickstart: ./user-guide/login.md
              - Ingress: ./user-guide/ingress.md
              - Logging: ./user-guide/logging.md
              - Templating:  ./user-guide/templating.md
        - Production Runtime:
                - Overview: ./admin-guide/runtime.md
                - Cert Manager: ./admin-guide/cert-manager.md
                - Single Sign On: ./admin-guide/sso.md
                - DBaaS (Postgres): ./admin-guide/postgres.md
                - Consul: ./admin-guide/consul.md
                - Open Policy Agent: ./admin-guide/opa.md
                - Elastic on K8S: ./admin-guide/eck.yml
                - Image Registry (Harbor): ./admin-guide/harbor.md
                - Monitoring: ./admin-guide/monitoring.md
                - Vault: ./admin-guide/vault.md
        - Administrator Guide:
                - Quickstart with vSphere: ./admin-guide/provisioning/vsphere.md
                - Quickstart with Kind: ./admin-guide/provisioning/kind.md
                - NSX NCP: ./admin-guide/ncp.md
                - Configuration: ./admin-guide/configuration.md
                - Backup/Restore: ./admin-guide/backup.md
                - Persistent Volumes: ./admin-guide/persistent-volumes.md
                - Multi-Tenancy: ./admin-guide/index.md
                - Auditing: ./admin-guide/auditing.md
                - Encryption: ./admin-guide/Encryption.md
                - Sealed Secrets: ./admin-guide/sealed_secrets.md
        - Developer Guide:
                - Quickstart: ./developer-guide/index.html#quickstart
                - Documentation: ./developer-guide/index.html#documentation
                - Common Issues: ./developer-guide/index.html#common-issues
                - Mocks/Stubs: ./developer-guide/index.html#common-issues
                - Reference: ./developer-guide/make-targets.md
        - Reference:
                - CLI: ./cli/platform-cli.md
                - Configuration: ./reference/config.md
