version: 2
go: &go
  environment:
    GO111MODULE: "on"
    GOPROXY: https://proxy.golang.org
  docker:
    - image: circleci/golang:1.12
  working_directory: /go/src/github.com/moshloop/platform-cli
jobs:
  test15:
    resource_class: large
    environment:
      VERSION: v1.15.3
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: ./test/e2e.sh
      - store_test_results:
          path: test-results

  test16:
    resource_class: large
    environment:
      VERSION: v1.16.3
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: ./test/e2e.sh
      - store_test_results:
          path: test-results

  release:
    <<: *go
    steps:
      - checkout
      - setup_remote_docker
      - run: go mod download
      - run: ./scripts/release.sh

workflows:
  version: 2
  build:
    jobs:
      - test15
      - test16
      - release:
          requires:
            - test15
            - test16
          context: Github
          filters:
            tags:
              only: /.*/
