version: 2
go: &go
  environment:
    GO111MODULE: "on"
    CGO_ENABLED: 0
    GOPROXY: https://proxy.golang.org
  docker:
    - image: circleci/golang:1.13
  working_directory: /go/src/github.com/flanksource/karina
jobs:
  lint:
    <<: *go
    resource_class: xlarge
    steps:
      - checkout
      - run: go run test/linter/main.go
      - run: ./scripts/golint.sh
      - store_test_results:
          path: test-results
  test:
    resource_class: xlarge
    environment:
      VERSION: v1.15.3
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: ./test/e2e.sh
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: artifacts

  test-next:
    resource_class: xlarge
    environment:
      VERSION: v1.16.3
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: ./test/e2e.sh
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: artifacts

  release-docs:
    docker:
      - image: flanksource/build-tools
    steps:
      - checkout
      - run: ./scripts/release-docs.sh

workflows:
  version: 2
  build:
    jobs:
      - test
      - test-next
      - lint
