apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          args:
            - "--upstream=file:///dev/null"
            - "--http-address=0.0.0.0:4180"
            - "--whitelist-domain=.{{.domain}}"
            - "--cookie-domain=.{{.domain}}"
            - "--provider=oidc"
            - "--provider-display-name=Dex"
            - "--client-id=kubernetes"
            - "--client-secret=ZXhhbXBsZS1hcHAtc2VjcmV0"
            - "--redirect-url=https://oauth2.{{.domain}}/oauth2/callback"
            - "--oidc-issuer-url=https://dex.{{.domain}}"
            - "--scope=openid email groups profile"
            - "--skip-oidc-discovery"
            - "--login-url=https://dex.{{.domain}}/auth"
            - "--redeem-url=https://dex.dex.svc:443/token"
            - "--ssl-insecure-skip-verify"
            - "--oidc-jwks-url=https://dex.dex.svc/keys"
            - "--cookie-secure=true"
            - "--email-domain=*"
            - "--pass-authorization-header=true"
            - "--pass-host-header=true"
            - "--pass-access-token=true"
            - "--set-xauthrequest=true"
            - "--set-authorization-header=true"
            - "--request-logging=true"
            {{ if (index . "oauth2Proxy") }}
            {{ if (index .oauth2Proxy "redis") }}
            {{ if .oauth2Proxy.redis.enabled }}
            - --redis-insecure-skip-tls-verify
            - --redis-use-sentinel
            - --redis-sentinel-connection-urls=redis://rfs-oauth2-proxy.ingress-nginx.svc.cluster.local:26379
            - --redis-sentinel-master-name=mymaster
            - --session-store-type=redis
            {{ end }}
            {{ end }}
            {{ end }}
          env:
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: oauth2-cookie-secret
          image: quay.io/oauth2-proxy/oauth2-proxy:{{.oauth2Proxy.version}}
          resources:
            requests:
              cpu: 25m
              memory: 100Mi
            limits:
              memory: 512Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 4180
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: ingress-nginx
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: ingress-nginx
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: oauth2.{{.domain}}
      http:
        paths:
          - backend:
              serviceName: oauth2-proxy
              servicePort: 4180
            path: /oauth2
  tls:
    - secretName: oauth2-tls
      hosts:
        - oauth2.{{.domain}}
{{ if (index . "oauth2Proxy") }}
{{ if (index .oauth2Proxy "redis") }}
{{ if .oauth2Proxy.redis.enabled }}
---
apiVersion: db.flanksource.com/v1
kind: RedisDB
metadata:
  name: oauth2-proxy
  namespace: ingress-nginx
spec:
  storage:
    storageClass: {{.oauth2Proxy.redis.storageClass | default "local-path"}}
  redis:
    replicas: {{ .oauth2Proxy.redis.replicas | default 3 }}
  sentinel:
    replicas: {{ .oauth2Proxy.redis.sentinelReplicas | default 3}}
{{ end }}
{{ end }}
{{ end }}