apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sbannedimagetags
spec:
  crd:
    spec:
      names:
        kind: K8sBannedImageTags
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            tags:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sbannedimagetags

        kinds = { "Pod", "Deployment", "ReplicationController", "ReplicaSet", "DaemonSet", "StatefulSet", "Job", "CronJob"}

        get_container(kind) = input.review.object.spec.template.spec.containers[_] { kinds[kind] }
        get_container(kind) = input.review.object.spec.containers[_] { kind == "Pod" }
        get_container(kind) = input.review.object.spec.jobTemplate.spec.template.spec.containers[_] { kind == "CronJob" }

        violation[{"msg": msg}] {
          container := get_container(input.review.object.kind)
          img_split := split(container.image, ":")
          tag := img_split[count(img_split) - 1]
          banned := {s | s = input.parameters.tags[_]}
          banned[tag]
          msg := sprintf("container <%v> has banned image tag <%v>, banned tags are %v", [container.name, tag, banned])
        }
