apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: grafanas.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: Grafana
    listKind: GrafanaList
    plural: grafanas
    singular: grafana
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          properties:
            containers:
              type: array
              items:
                type: object
                description: Additional container to add to the grafana pod
            secrets:
              type: array
              items:
                type: string
                description: Secret to be mounted as volume into the grafana deployment
            configMaps:
              type: array
              items:
                type: string
                description: Config map to be mounted as volume into the grafana deployment
            logLevel:
              type: string
              description: Log level of the grafana instance, defaults to info
            adminUser:
              type: string
              description: Default admin user name
            adminPassword:
              type: string
              description: Default admin password
            basicAuth:
              type: boolean
              description: Basic auth enabled
            disableLoginForm:
              type: boolean
              description: Disable login form
            disableSignoutMenu:
              type: boolean
              description: Disable signout menu
            anonymous:
              type: boolean
              description: Anonymous auth enabled
            config:
              type: object
              description: Grafana config
            ingress:
              type: object
              properties:
                enabled:
                  type: boolean
                  description: Create an ingress / route
                path:
                  type: string
                  description: Ingress path
                hostname:
                  type: string
                  description: The hostname of the ingress / route
                annotations:
                  type: object
                  description: Additional annotations for the ingress / route
                labels:
                  type: object
                  description: Additional labels for the ingress / route
                targetPort:
                  type: string
                  description: Override port to target in the grafana service
            service:
              type: object
              properties:
                ports:
                  type: array
                  description: Override default ports
                  items:
                    type: object
                    descripton: A port to add to the grafana service
                annotations:
                  type: object
                  description: Additional annotations for the service
                labels:
                  type: object
                  description: Additional labels for the service
                type:
                  type: string
                  description: Service type (NodePort, ClusterIP or LoadBalancer)
            deployment:
              type: object
              properties:
                annotations:
                  type: object
                  description: Additional annotations for the service
                labels:
                  type: object
                  description: Additional labels for the service
            serviceAccount:
              type: object
              properties:
                annotations:
                  type: object
                  description: Additional annotations for the serviceaccount
                labels:
                  type: object
                  description: Additional labels for the serviceaccount
            client:
              type: object
              description: Grafana client settings
            compat:
              type: object
              description: Backwards compatibility switches
            dashboardLabelSelectors:
              type: array
              items:
                type: object
                description: Label selector or match expressions
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: grafanadashboards.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: GrafanaDashboard
    listKind: GrafanaDashboardList
    plural: grafanadashboards
    singular: grafanadashboard
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            name:
              type: string
            json:
              type: string
            plugins:
              type: array
              items:
                description: Grafana Plugin Object
                type: object
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: grafanadatasources.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: GrafanaDataSource
    listKind: GrafanaDataSourceList
    plural: grafanadatasources
    singular: grafanadatasource
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          required: ["datasources", "name"]
          properties:
            name:
              type: string
              minimum: 1
            datasources:
              type: array
              items:
                description: Grafana Datasource Object
                type: object
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-operator
rules:
  - apiGroups:
      - integreatly.org
    resources:
      - grafanadashboards
      - grafanadashboards/status
    verbs: ["get", "list", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-operator
subjects:
  - kind: ServiceAccount
    name: grafana-operator
    namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-operator
  namespace: monitoring
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - serviceaccounts
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - "*"
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - integreatly.org
    resources:
      - grafanas
      - grafanas/status
      - grafanas/finalizers
      - grafanadashboards
      - grafanadashboards/status
      - grafanadatasources
      - grafanadatasources/status
    verbs:
      - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-operator
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: grafana-operator
    namespace: monitoring
roleRef:
  kind: Role
  name: grafana-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-operator
  namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-operator
  namespace: monitoring
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      name: grafana-operator
  template:
    metadata:
      labels:
        name: grafana-operator
      annotations:
        com.flanksource.infra.logs/processors.0.drop_event.when.contains.message: SUCCESS
        com.flanksource.infra.logs/processors.1.drop_event.when.contains.message: running periodic dashboard resync
        com.flanksource.infra.logs/processors.2.decode_json_fields.fields: message
        com.flanksource.infra.logs/processors.2.decode_json_fields.target: ""
    spec:
      serviceAccountName: grafana-operator
      containers:
        - name: grafana-operator
          image: quay.io/integreatly/grafana-operator:v3.1.0
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 256Mi
          args:
            - "--grafana-image=docker.io/grafana/grafana"
            - "--grafana-image-tag=6.6.2"
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - grafana-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: TEMPLATE_PATH
              value: /usr/local/bin/templates
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "grafana-operator"
