name: Kind Binary

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 12 * * *'
  # temporary just to test on PR
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  binary:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools:0.6
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@master
      - run: make pack linux
      - uses: actions/upload-artifact@v2
        with:
          name: karina
          path: ./.bin/karina
  kind-image:
    runs-on: ubuntu-latest
    needs: binary
    strategy:
      matrix:
        k8s:
          - v1.16.9
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v2
        with:
          name: karina
          path: ./.bin
      - name: Get release version
        id: get_version
        run: echo ::set-env name=DOCKER_TAG::${{matrix.k8s}}-$(date +%Y%m%d%M%H%M%S)
      - name: Run generate kind image
        env:
          KIND_NODE_VERSION: ${{matrix.k8s}}
          DOCKER_IMAGE: flanksource/kind-node
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
          DEPLOY_KIND_CLUSTER: "true"
        run: ./scripts/generate_kind_image.sh
      - name: Publish to Registry2
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: flanksource/kind-node:${{ env.DOCKER_TAG }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
          snapshot: true